apiVersion: apps/v1

kind: Deployment

metadata:

 name: my-deployment

spec:

 replicas: 3

 selector:

   matchLabels:

     app: my-app

 template:

   metadata:

     labels:

       app: my-app

   spec:

     containers:

       - name: my-container

         image: my-container-image:latest

         ports:

           - containerPort: 80
---
apiVersion: v1

kind: Pod

metadata:

  name: my-pod

spec:

  containers:

    - name: my-container

      image: my-container-image:tag
