# Use the official Node.js 14.x base image

FROM node:14

 

# Set the working directory inside the container

WORKDIR /app

 

# Copy package.json and package-lock.json to the working directory

COPY package*.json ./

 

# Install dependencies

RUN npm install

 

# Copy the rest of the application code to the working directory

COPY . .

 

# Expose port 3000 for the application

EXPOSE 3000

 

# Define the startup command to run the application

CMD ["node", "app.js"]
